development:
  paypal_email: luddit_1332703378_biz@gmail.com
  paypal_secret: bananameritocracy
  paypal_cert_id: M6UDH3QBXP4JU
  paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr

test:
  paypal_email: luddit_1332703378_biz@gmail.com
  paypal_secret: bananameritocracy
  paypal_cert_id: M6UDH3QBXP4JU
  paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr

production:
  paypal_email: luddit_1332703378_biz@gmail.com
  paypal_secret: bananameritocracy
  paypal_cert_id: M6UDH3QBXP4JU
  paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
